[package]
name = "apple-accelerate"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
paste = "1.0.14"
rustfft = "6.1.0"

[dependencies]
num-complex = "0.4.4"

# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"
